// This file was auto-generated by Fern from our API Definition.
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
import * as core from "../core/index.mjs";
/**
 * Verify an HMAC webhook signature.
 *
 * Extract the signature from the "x-webhook-signature" header and pass it as the signatureHeader parameter.
 */
export class WebhooksHelper {
    static verifySignature(requestBody, signatureHeader, signatureKey) {
        return __awaiter(this, void 0, void 0, function* () {
            if (requestBody == null || signatureHeader == null || signatureKey == null) {
                return false;
            }
            const payload = requestBody;
            const expected = yield core.computeHmacSignature({
                payload: payload,
                secret: signatureKey,
                algorithm: "sha256",
                encoding: "hex",
            });
            return yield core.timingSafeEqual(signatureHeader, expected);
        });
    }
}
